# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile - Intel MIC Linux driver.
# Copyright(c) 2016, Intel Corporation.
#
obj-$(CONFIG_FINGERPRINT_GOODIX) := goodix_fp.o

goodix_fp-objs += gf_spi.o
goodix_fp-objs += platform.o
goodix_fp-objs += netlink.o

