#for AW8680X touch Driver
obj-$(CONFIG_TOUCH_AW8680X) += aw8680x_ftouch.o

aw8680x_ftouch-y := aw8680x.o aw_bin_parse.o aw_soc_protocol_interface.o aw_com_protocol.o \
	aw_protocol_fun.o aw_protocol_map.o
