obj-$(CONFIG_AWINIC_HAPTIC_HV)	+= haptic.o
haptic-objs			:= aw869x.o aw869xx.o aw8671x.o aw8692x.o haptic_hv.o

obj-$(CONFIG_AWINIC_8691X_HAPTIC_HV)	+= aw8691x_haptic.o
aw8691x_haptic-objs			:= aw869xx.o haptic_hv.o
